version: "2"
services:
  boilerplate-api-angel:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/angel
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb-angel

  mongodb-angel:
    image: mongo
    ports:
      - "27017:27017"
