version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/angel
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
